version: '3'

services:

    users:
        build:
            context: ./microservices/users
            network: host
        restart: always
        volumes:
            - ./microservices/users/app:/code/app
            - ./microservices/users/logs:/logs
        depends_on:
            db:
                condition: service_healthy
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            # POSTGRES_USER: postgres
            # POSTGRES_PASSWORD: changeme
            POSTGRES_DB: pgdb
        healthcheck:
            test: curl --fail http://localhost:8888/users || exit 1
            interval: 10s
            retries: 5
            start_period: 20s
            timeout: 10s

    banks:
        build:
            context: ./microservices/banks
            network: host
        restart: always
        volumes:
            - ./microservices/banks/app:/code/app
            - ./microservices/banks/logs:/logs
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: curl --fail http://localhost:8888/banks || exit 1
            interval: 10s
            retries: 5
            start_period: 20s
            timeout: 10s

    transactions:
        build:
            context: ./microservices/transactions
            network: host
        restart: always
        volumes:
            - ./microservices/transactions/app:/code/app
            - ./microservices/transactions/logs:/logs
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: curl --fail http://localhost:8888/transactions || exit 1
            interval: 10s
            retries: 5
            start_period: 20s
            timeout: 10s

    nginx:
        image: nginx:latest
        ports:
            - '8080:80'
        volumes:
            - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - users
            - banks
            - transactions

    db:
        image: postgres:alpine3.15
        container_name: db
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            # POSTGRES_USER: postgres
            # POSTGRES_PASSWORD: changeme
            POSTGRES_DB: pgdb
            # POSTGRES_HOST: db
            # POSTGRES_HOST_AUTH_METHOD: trust
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - '5432:5432'
        # extra_hosts:
        #     - "db:127.0.0.1" #host and ip
        restart: always
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5

    # pgadmin:
    #     image: dpage/pgadmin4:6.4
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
    #         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    #         PGADMIN_CONFIG_SERVER_MODE: 'False'
    #     volumes:
    #         - pgadmin:/var/lib/pgadmin

    #     ports:
    #         - '${PGADMIN_PORT:-5050}:80'
    #     restart: unless-stopped
    
volumes:
    postgres:
    # pgadmin:
